apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-vol
    ports:
    - containerPort: 3306
    envFrom:
    - configMapRef:
        name: configmap-mysql
  volumes:
  - name: mysql-vol
    hostPath:
      path: /data
      type: DirectoryOrCreate
