apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    storage: pv-nfs
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.103
    path: /data
