apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-app
  labels:
    k8s-app: daemonset-app
spec:
  selector:
    matchLabels:
      name: daemonset-app
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        name: daemonset-app
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: daemonset-app
        image: takytaky/app:v3
        env:
        - name: appenv 
          value: daemonset
